### ISSUE TITLE
Google search behind VPN crashes program sporadically

### ISSUE THREAD

**Issue by ajmeese7** [mxrch/GitFive#15]
Due to the sensitive nature of my investigation I cannot share the true username or company name, so those are changed in this log:

```log
$ gitfive user *username-here* --json username-GitHub.json

...

[Gists]
Nothing to show.

Traceback (most recent call last):
  File "/home/aaron/.local/bin/gitfive", line 8, in <module>
    sys.exit(main())
  File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/gitfive.py", line 14, in main
    parse_args()
  File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/cli.py", line 51, in parse_args
    trio.run(username_mod.hunt, args.username, args.json)
  File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/modules/username_mod.py", line 102, in hunt
    out = guess_custom_domain(runner)
  File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/domain_finder.py", line 18, in guess_custom_domain
    for url in search(company):
  File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/googlesearch/__init__.py", line 45, in search
    resp = _req(escaped_term, num_results-start, lang, start, proxies)
  File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/googlesearch/__init__.py", line 18, in _req
    resp.raise_for_status()
  File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dcompanynamehere%26num%3D12%26hl%3Den%26start%3D0&hl=en&q=EgQlE8gEGLTm6JsGIjB-cLs3q0J6nSqP_APHJ94swg-1WDU3M5bxIrKF8LlzUWdpW_TlfmljxD4kp0T2CioyAXI
```

I believe this is because I am running my queries behind Proton VPN and Google flags the traffic as suspicious, but the program could be improved by gracefully failing and skipping the company lookup with a helpful warning message as opposed to erroring out and preventing the user from getting any further information.

I can take a stab at this if you'd like, but if you'd prefer to implement it in your style that works just as well. Shouldn't take too long to implement from what I can tell, it would just be wrapping `search(company)` in a try-catch statement.

**Comment by mxrch** [comment]
You're right, I'll make a try and catch statement for it soon. Thanks !

**Comment by mxrch** [comment]
@ajmeese7 can you re-test using the light-update branch ?
To avoid using pipx, you can just use `python3 main.py <module>`

**Comment by ajmeese7** [comment]
Looks great man, thanks for the incredibly quick turnaround time! Closing this issue out now 🎉
