### ISSUE TITLE
Bug: AttributeError: 'types.SimpleNamespace' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by SSSEAL-C** [mxrch/GitFive#19]
Operating System:
`Windows 10.0.19044 Build 19044`

Traceback:
```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\username\.local\bin\gitfive.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\gitfive\gitfive.py", line 15, in main
    parse_args()
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\gitfive\lib\cli.py", line 51, in parse_args
    trio.run(username_mod.hunt, args.username, args.json)
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\trio\_core\_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\gitfive\modules\username_mod.py", line 191, in hunt
    emails_accounts = await commits.scrape(runner, temp_repo_name, emails_index)
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\gitfive\lib\commits.py", line 94, in scrape
    async with trio.open_nursery() as nursery:
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\trio\_core\_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\gitfive\lib\commits.py", line 56, in fetch_commits
    async with trio.open_nursery() as nursery:
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\trio\_core\_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\gitfive\lib\commits.py", line 31, in fetch_avatar
    runner.rc.print(f"[+] [TARGET FOUND] 🐱 {email} -> @{username}{_name_str}", style="green bold")
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\rich\console.py", line 1667, in print
    with self:
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\rich\console.py", line 869, in __exit__
    self._exit_buffer()
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\rich\console.py", line 827, in _exit_buffer
    self._check_buffer()
  File "C:\Users\username\.local\pipx\venvs\gitfive\lib\site-packages\rich\console.py", line 2011, in _check_buffer
    self.file.fileno() in _STD_STREAMS_OUTPUT
AttributeError: 'types.SimpleNamespace' object has no attribute 'fileno'
```

Command Used:
`gitfive user mxrch`

**Comment by mxrch** [comment]
Can't reproduce.
Does the problem persists ?

**Comment by SSSEAL-C** [comment]
Yup I can still achieve it. I think its an issue due to rich characters like unicode.

**Comment by mxrch** [comment]
@SSSEAL-C Are you running it again inside NodeJS ?

Otherwise, which terminal are you using ?

**Comment by SSSEAL-C** [comment]
Just default windows, no nodeJS. I think its something weird with runner as changing it to normal print works...
