### ISSUE TITLE
Bug: UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f426' in position 0: character maps to <undefined>

### ISSUE THREAD

**Issue by SSSEAL-C** [mxrch/GitFive#20]
Attempting to execute in nodeJS exec.

**Traceback**:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\username\.local\bin\gitfive.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\gitfive\gitfive.py", line 14, in main
    show_banner()
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\gitfive\lib\utils.py", line 104, in show_banner
    rprint(banner)
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\rich\__init__.py", line 74, in print
    return write_console.print(*objects, sep=sep, end=end)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\rich\console.py", line 1667, in print
    with self:
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\rich\console.py", line 869, in __exit__
    self._exit_buffer()
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\rich\console.py", line 827, in _exit_buffer
    self._check_buffer()
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\rich\console.py", line 2024, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\username\.local\pipx\venvs\gitfive\Lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f426' in position 0: character maps to <undefined>
```

**OS**: Windows 10.0.19044 Build 19044
**Python Ver**: 3.11.0

**Comment by mxrch** [comment]
I don't provide support for integration in other languages (PS : plz don't open this issue in each Python projects, you see that it's a problem related to the Rich lib 😭 )
