### ISSUE TITLE
Breaks when "Impersonating users got in dumped commits"

### ISSUE THREAD

**Issue by ajmeese7** [mxrch/GitFive#23]
The start of the program worked fine, then it errored out like so:

```shell
🎭 IDENTITIES UNMASKING

[XRAY] 🎭 Impersonating users got in dumped commits...
Traceback (most recent call last):
File "/home/aaron/.local/bin/gitfive", line 8, in <module>
sys.exit(main())
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/gitfive.py", line 15, in main
parse_args()
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/cli.py", line 51, in parse_args
trio.run(username_mod.hunt, args.username, args.json)
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
raise runner.main_task_outcome.error
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/modules/username_mod.py", line 175, in hunt
await xray.analyze(runner)
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/xray.py", line 248, in analyze
temp_repo_name, emails_index = await metamon.start(runner, emails_candidates)
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/metamon.py", line 77, in start
repo = Repo.init(repo_path, initial_branch='mirage')
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/git/repo/base.py", line 1046, in init
git.init(**kwargs)
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/git/cmd.py", line 639, in <lambda>
return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/git/cmd.py", line 1184, in _call_process
return self.execute(call, **exec_kwargs)
File "/home/aaron/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/git/cmd.py", line 984, in execute
raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
cmdline: git init --initial-branch=mirage
stderr: 'error: unknown option `initial-branch=mirage'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

--template <template-directory>
directory from which templates will be used
--bare                create a bare repository
--shared[=<permissions>]
specify that the git repository is to be shared amongst several users
-q, --quiet           be quiet
--separate-git-dir <gitdir>
separate git dir from working tree
'
```

I am running the latest version of GitFive, I ran `pipx uninstall gitfive; pipx install gitfive --python $(which python3.10) --force` immediately beforehand. I am running `git version 2.25.1` if that's a factor at play here.

**Comment by mxrch** [comment]
Hey, can you update git to the last version and retry ?
Seems like a duplicate of #7.

**Comment by ajmeese7** [comment]
Yikes, I didn't realize Ubuntu shipped with such an old version of Git! I thought I had the latest version, I'm really behind the times 😅 

Updating with the PPA repository fixed the issue, thanks!
