### ISSUE TITLE
trio.NonBaseMultiError: AttributeError("'types.SimpleNamespace' object has no attribute 'fileno'"), AttributeError("'types.SimpleNamespace' object has no attribute 'fileno'")

### ISSUE THREAD

**Issue by sealldeveloper** [mxrch/GitFive#24]
This error sometimes appears with users that have large follower/following or lots of commits. Just after Metamon adds the commits this appears. 

Error: `trio.NonBaseMultiError: AttributeError("'types.SimpleNamespace' object has no attribute 'fileno'"), AttributeError("'types.SimpleNamespace' object has no attribute 'fileno'")`

Traceback: 
```
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Scripts\gitfive-script.py", line 33, in <module>
  |     sys.exit(load_entry_point('gitfive==1.1.0', 'console_scripts', 'gitfive')())
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\gitfive-1.1.0-py3.11.egg\gitfive\gitfive.py", line 15, in main
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\gitfive-1.1.0-py3.11.egg\gitfive\lib\cli.py", line 51, in parse_args
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\trio\_core\_run.py", line 2010, in run
  |     raise runner.main_task_outcome.error
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\gitfive-1.1.0-py3.11.egg\gitfive\modules\username_mod.py", line 175, in hunt
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\gitfive-1.1.0-py3.11.egg\gitfive\lib\xray.py", line 251, in analyze
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\gitfive-1.1.0-py3.11.egg\gitfive\lib\commits.py", line 94, in scrape
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\trio\_core\_run.py", line 850, in __aexit__
  |     raise combined_error_from_nursery
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\gitfive-1.1.0-py3.11.egg\gitfive\lib\commits.py", line 56, in fetch_commits
  |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\trio\_core\_run.py", line 850, in __aexit__
  |     raise combined_error_from_nursery
  | trio.NonBaseMultiError: AttributeError("'types.SimpleNamespace' object has no attribute 'fileno'"), AttributeError("'types.SimpleNamespace' object has no attribute 'fileno'")
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\gitfive-1.1.0-py3.11.egg\gitfive\lib\commits.py", line 17, in fetch_avatar
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich-12.6.0-py3.11.egg\rich\console.py", line 1667, in print
    |     with self:
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich-12.6.0-py3.11.egg\rich\console.py", line 869, in __exit__
    |     self._exit_buffer()
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich-12.6.0-py3.11.egg\rich\console.py", line 827, in _exit_buffer
    |     self._check_buffer()
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich-12.6.0-py3.11.egg\rich\console.py", line 2011, in _check_buffer
    |     self.file.fileno() in _STD_STREAMS_OUTPUT
    |     ^^^^^^^^^^^^^^^^
    | AttributeError: 'types.SimpleNamespace' object has no attribute 'fileno'
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\gitfive-1.1.0-py3.11.egg\gitfive\lib\commits.py", line 17, in fetch_avatar
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich-12.6.0-py3.11.egg\rich\console.py", line 1667, in print
    |     with self:
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich-12.6.0-py3.11.egg\rich\console.py", line 869, in __exit__
    |     self._exit_buffer()
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich-12.6.0-py3.11.egg\rich\console.py", line 827, in _exit_buffer
    |     self._check_buffer()
    |   File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich-12.6.0-py3.11.egg\rich\console.py", line 2011, in _check_buffer
    |     self.file.fileno() in _STD_STREAMS_OUTPUT
    |     ^^^^^^^^^^^^^^^^
    | AttributeError: 'types.SimpleNamespace' object has no attribute 'fileno'
    +------------------------------------
```

OS: Windows 10.0.19044 Build 19044
Python Ver: 3.11.0

**Comment by Rycoh99** [comment]
hello, did you manage to fix it?

**Comment by sealldeveloper** [comment]
I haven't gotten the error since, but it happens occasionally. I don't know what causes it but redoing the request or a reinstall seems to work. Sometimes `pipx ensurepath` helps aswell. No idea...

**Comment by mxrch** [comment]
I can't reproduce, never had it. Feel free to re-open the issue if it happens to someone else.

**Comment by Cystemzz** [comment]
I had this issue as well whilst running GitFive within cmd. Upon switching to Windows Terminal/Powershell it was fixed, I believe this issue is to do with console output, however I haven't had too much time to check it out. I'll try to take a closer look in the morning.
