### ISSUE TITLE
error gitfive cant use it 

### ISSUE THREAD

**Issue by zemdkimd** [mxrch/GitFive#34]
Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hackn\Downloads\GitFive-master(1)\GitFive-master\main.py", line 2, in <module>
    from gitfive import gitfive; gitfive.main()
                                 ^^^^^^^^^^^^^^
  File "C:\Users\hackn\Downloads\GitFive-master(1)\GitFive-master\gitfive\gitfive.py", line 15, in main
    parse_args()
  File "C:\Users\hackn\Downloads\GitFive-master(1)\GitFive-master\gitfive\lib\cli.py", line 48, in parse_args
    from gitfive.modules import username_mod
  File "C:\Users\hackn\Downloads\GitFive-master(1)\GitFive-master\gitfive\modules\username_mod.py", line 5, in <module>
    from gitfive.lib import metamon
  File "C:\Users\hackn\Downloads\GitFive-master(1)\GitFive-master\gitfive\lib\metamon.py", line 2, in <module>
    from git import Repo
  File "C:\Users\hackn\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\__init__.py", line 89, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
    
    
    
    
    i updated all repo and all still.

**Comment by mxrch** [comment]
Read the output. Install git, or reinstall it correctly.
