### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by r0mantical** [mxrch/GitFive#35]
Python 3.11.3, latest GitFive using pipx

```
[+] 78 potential emails generated !
[METAMON] 🐙 Added commits in 9.03s !

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\synth\.local\bin\gitfive.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\gitfive\gitfive.py", line 15, in main
    parse_args()
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\gitfive\lib\cli.py", line 51, in parse_args
    trio.run(username_mod.hunt, args.username, args.json)
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\trio\_core\_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\gitfive\modules\username_mod.py", line 191, in hunt
    emails_accounts = await commits.scrape(runner, temp_repo_name, emails_index)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\gitfive\lib\commits.py", line 94, in scrape
    async with trio.open_nursery() as nursery:
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\trio\_core\_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\gitfive\lib\commits.py", line 56, in fetch_commits
    async with trio.open_nursery() as nursery:
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\trio\_core\_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\gitfive\lib\commits.py", line 25, in fetch_avatar
    full_name = await github.fetch_profile_name(runner, username)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\synth\.local\pipx\venvs\gitfive\Lib\site-packages\gitfive\lib\github.py", line 69, in fetch_profile_name
    fields = [x.text.strip() for x in body.find("section", {"aria-label": "user login and name"}).find_all("a")]
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by DeaganGHCP** [comment]
same issue

**Comment by sierradeltapappa** [comment]
Same issue

**Comment by mxrch** [comment]
Yes GitHub change something, I'll take a look rn

**Comment by mxrch** [comment]
It was caused because GitHub changed an aria-label from `user login and name` to `User login and name`.... 😩 
I pushed the fix in https://github.com/mxrch/GitFive/commit/e5e9e89425435f49861db4e03322a35be6fd5a0f and on PyPI, please upgrade with `pipx upgrade gitfive` ! ❤️
