### ISSUE TITLE
Failed in repository stats 

### ISSUE THREAD

**Issue by Miguel000** [mxrch/GitFive#36]
Hi, 
I tried to use the tool for my user and received this error:

```
🏭 REPOSITORIES STATS

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/gitfive", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/gitfive.py", line 15, in main
    parse_args()
  File "/home/ubuntu/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/cli.py", line 51, in parse_args
    trio.run(username_mod.hunt, args.username, args.json)
  File "/home/ubuntu/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/ubuntu/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/modules/username_mod.py", line 144, in hunt
    await repos.get_list(runner)
  File "/home/ubuntu/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/repos.py", line 55, in get_list
    total_repos = int(body.find("span", {"class": "Counter"}).attrs["title"])
ValueError: invalid literal for int() with base 10: 'Beta'
```
I've followed the installation instructions and logged in with a secondary account, am I missing a step? Thanks in advance

**Comment by peasead** [comment]
Same issue.

**Comment by mxrch** [comment]
Yes, it needs a fix. I hope someone can help.

**Comment by c-um** [comment]
If you want a rough fix which I don't recommend - open up repos.py in IDLE or whatever code editor you use and replace:
<br> `req = await runner.as_client.get(f"https://github.com/{runner.target.username}?tab=repositories")` <br>
With:
<br> `req = requests.get(f"https://github.com/{runner.target.username}?tab=repositories")` <br>
Make sure to also put `import requests` up top - I'm not sure what is causing the error exactly and can't be bothered investigating at the moment, however this just works.

**Comment by peasead** [comment]
Thanks, this worked.

In the event anyone is looking for `repos.py`, it's here:
```
.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/repos.py
```

Also, why don't you recommend this fix?

**Comment by c-um** [comment]
> Thanks, this worked.
> 
> In the event anyone is looking for `repos.py`, it's here:
> 
> ```
> .local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/repos.py
> ```
> 
> Also, why don't you recommend this fix?

It is due to the fact that it *might* not be very stable - as mxrch uses an asynchronous httpx request instead of a normal request. Therefore I am not sure if it would actually be affecting anything major.

**Comment by mxrch** [comment]
Fixed
