### ISSUE TITLE
Error encountered when trying to track a user with a private profile

### ISSUE THREAD

**Issue by sealldeveloper** [mxrch/GitFive#40]
Expected Result: Display any information it can find on the private profile user, even if minimal

Actual Result:
```
Traceback (most recent call last):
  File "/.../bin/gitfive", line 8, in <module>
    sys.exit(main())
  File "/.../python3.10/site-packages/gitfive/gitfive.py", line 15, in main
    parse_args()
  File "/.../python3.10/site-packages/gitfive/lib/cli.py", line 51, in parse_args
    trio.run(username_mod.hunt, args.username, args.json)
  File "/.../python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/.../python3.10/site-packages/gitfive/modules/username_mod.py", line 35, in hunt
    await analyze_ext_contribs(runner)
  File "/.../python3.10/site-packages/gitfive/lib/xray.py", line 319, in analyze_ext_contribs
    if total_count > 100:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by Lexterl33t** [comment]
Can you send the profile of the user?

**Comment by sealldeveloper** [comment]
> Can you send the profile of the user?

It just needs to be the profile of any user on private mode.
