### ISSUE TITLE
2FA issue: AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by soxoj** [mxrch/GitFive#41]
Installed by instruction with pipx, default python3 version is 3.11.5.

```sh
$ gitfive user soxoj




                   %%                   %%
                 (%%%%%,             (%%%%%,
                 %%%%%@@@@@@@@@@@@@@@@@%%%%%
                 %%%@@@@@@@@@(((@@@@@@@@@%%%
                 @@@@@@((@@@(((@@@((@@@@@@%
                 @@@@@@@((((@@@@@((((@@@@@@@
                @@@@((((@@&(@@@@@(@@@((((@@@@
               @@@@@(((((@@@@@@@@@@@((((%@@@@@
               @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
               @@@@@@@@@@@@@.....@@@@@@@@@@@@@
               @@@@@@@@@@@@@@@.@@@@@@@@@@@@@@@
                 @@@@@@@@@@@@,,,@@@@@@@@@@@@
           (((      @@@@@@@@@@@@@@@@@@@
              *((          @@@@@@@
                *((       @@@@@@@@@
                  (((((. @@@@@@@@@@@
                    (((((@@@@@@@@@@@&
                        @@@@@@@@@@@@@
                        @@@@@@@@@@@@@
                        .@@@@@@@@@@@#

                  By: mxrch (🐦 @mxrchreborn)
            Support my work on GitHub Sponsors ! 💖


[DEBUG] Cookies no more active, I re-login...
[+] Credentials found !

Checking API token validity...
[+] Token valid ! (scopes : delete_repo and repo)

[*] 2FA
Traceback (most recent call last):
  File "/Users/account/.local/bin/gitfive", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/account/.local/pipx/venvs/gitfive/lib/python3.11/site-packages/gitfive/gitfive.py", line 15, in main
    parse_args()
  File "/Users/account/.local/pipx/venvs/gitfive/lib/python3.11/site-packages/gitfive/lib/cli.py", line 51, in parse_args
    trio.run(username_mod.hunt, args.username, args.json)
  File "/Users/account/.local/pipx/venvs/gitfive/lib/python3.11/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/Users/account/.local/pipx/venvs/gitfive/lib/python3.11/site-packages/gitfive/modules/username_mod.py", line 19, in hunt
    await runner.login()
  File "/Users/account/.local/pipx/venvs/gitfive/lib/python3.11/site-packages/gitfive/lib/objects.py", line 489, in login
    await self.creds.check_and_login()
  File "/Users/account/.local/pipx/venvs/gitfive/lib/python3.11/site-packages/gitfive/lib/objects.py", line 343, in check_and_login
    await self.login()
  File "/Users/account/.local/pipx/venvs/gitfive/lib/python3.11/site-packages/gitfive/lib/objects.py", line 308, in login
    authenticity_token = body.find("form", {"action": "/sessions/two-factor"}).find("input", {"name": "authenticity_token"}).attrs["value"]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by kittygirlyy** [comment]
I got the same error

**Comment by ProtDos** [comment]
> [@mxrch](https://github.com/mxrch) any updates?

The pull request #60 should solve this error.

**Comment by mxrch** [comment]
Fixed in #60
