### ISSUE TITLE
Return an error for when a profile is private

### ISSUE THREAD

**Issue by sealldeveloper** [mxrch/GitFive#45]
Currently when searching a hidden profile:
```
Traceback (most recent call last):
  File "/.../gitfive", line 8, in <module>
    sys.exit(main())
  File "/.../gitfive/gitfive.py", line 15, in main
    parse_args()
  File "/.../gitfive/lib/cli.py", line 51, in parse_args
    trio.run(username_mod.hunt, args.username, args.json)
  File "/.../_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/.../gitfive/modules/username_mod.py", line 35, in hunt
    await analyze_ext_contribs(runner)
  File "/.../gitfive/lib/xray.py", line 319, in analyze_ext_contribs
    if total_count > 100:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by soxoj** [comment]
+1, it's a common case, needs to be fixed
