### ISSUE TITLE
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)

### ISSUE THREAD

**Issue by tdeni** [mxrch/GitFive#7]
After `gitfive user %username` command.

Python 3.10.4 

```🎭 IDENTITIES UNMASKING

[XRAY] 🎭 Impersonating users got in dumped commits...
Traceback (most recent call last):
  File "/home/unnamed/.local/bin/gitfive", line 8, in <module>
    sys.exit(main())
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/gitfive.py", line 14, in main
    parse_args()
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/cli.py", line 51, in parse_args
    trio.run(username_mod.hunt, args.username, args.json)
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/modules/username_mod.py", line 157, in hunt
    await xray.analyze(runner)
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/xray.py", line 247, in analyze
    temp_repo_name, emails_index = await metamon.start(runner, emails_candidates)
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/gitfive/lib/metamon.py", line 77, in start
    repo = Repo.init(repo_path, initial_branch='mirage')
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/git/repo/base.py", line 1046, in init
    git.init(**kwargs)
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/unnamed/.local/pipx/venvs/gitfive/lib/python3.10/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git init --initial-branch=mirage
  stderr: 'error: unknown option `initial-branch=mirage'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree

**Comment by mxrch** [comment]
Hello, can you update git to the last version and retry ?

**Comment by tdeni** [comment]
Hey, everything works fine with git version 2.38.1. Thanks!
